image: Visual Studio 2017
init: 
  # Good practice, because Windows
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --info
build_script:
  - cmd: dotnet pack src/Neutrino.Seyren/Neutrino.Seyren.csproj --include-symbols /p:Version=$APPVEYOR_BUILD_VERSION -o ./
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
artifacts:
  - path: '**\*.nupkg'
    name: nuget
deploy:
  provider: NuGet
  api_key:
    secure: fGKXQRW8Nmbb213zBl818QwOd97xFOlgirR/7E719uUa5fFK5joHythNrdRHHhhR
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master